language: cpp
cache: ccache
sudo: required
dist: trusty
script:
 - sudo adduser --force-badname --system --home /nonexistent --no-create-home --quiet _apt || true
 - sudo chmod -R go+rwx /home/travis
 - sudo -u _apt test -d /home/travis
 - sudo -u _apt test -d /home/travis/build
 - sudo -u _apt test -d /home/travis/build/julian-klode
 - sudo -u _apt test -d /home/travis/build/julian-klode/apt
 - sudo -u _apt cat /home/travis/build/julian-klode/apt/README.md
 - sudo -u _apt touch /home/travis/build/julian-klode/apt/README.md
 
